use_frameworks!

platform :ios, '8.0'

target 'WGMutableArrayTool_Example' do
  pod 'WGMutableArrayTool', :path => '../'

  target 'WGMutableArrayTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
